project_name: nomad-service-discovery-exporter

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}.
      {{- .Version }}.
      {{- .Os }}-
      {{- .Arch }}

dockers:
  - use: buildx
    goos: linux
    goarch: amd64
    image_templates:
      - "ghcr.io/strigo/{{ .ProjectName }}:{{ .Version }}-amd64"
    build_flag_templates:
      - "--pull"
      - "--platform=linux/amd64"
  - use: buildx
    goos: linux
    goarch: arm64
    image_templates:
      - "ghcr.io/strigo/{{ .ProjectName }}:{{ .Version }}-arm64"
    build_flag_templates:
      - "--pull"
      - "--platform=linux/arm64"

docker_manifests:
- name_template: "ghcr.io/strigo/{{ .ProjectName }}:{{ .Version }}"
  image_templates:
    - "ghcr.io/strigo/{{ .ProjectName }}:{{ .Version }}-amd64"
    - "ghcr.io/strigo/{{ .ProjectName }}:{{ .Version }}-arm64"

checksum:
  name_template: "sha256sums.txt"
